version: 2
updates:

  # Maintain dependencies for terraform
  - package-ecosystem: "terraform"
    directory: "/"
    assignees:
      - "marek.moscichowski1"
      - "krzysztof.kluska"
      - "dawid.orzel"
      - "tomasz.sojka"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "task"
        versions: ["0.58.0"]
